## What is Numpy?

NumPy is a python library adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.


In [5]:
import numpy as np

In [6]:
np.__version__

'1.15.0'

#### Array Creation

In [7]:
zeros_arr = np.zeros(3)

In [8]:
zeros_arr

array([0., 0., 0.])

In [9]:
ones_arr = np.ones(3)

In [10]:
ones_arr

array([1., 1., 1.])

In [14]:
a = np.array([(1,2,3),(4,5,6)])

In [12]:
arr = np.array([1,2,3,4])

In [13]:
arr

array([1, 2, 3, 4])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

#### Numpy Array Dimension

In [18]:
a.ndim

2

In [19]:
arr = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])

print(arr[0, 1, 2])

6


In [20]:
arr.ndim

3

### Explanation
#### The first number represents the first dimension, which contains two arrays:
#### [[1, 2, 3], [4, 5, 6]]
####         &
#### [[7, 8, 9], [10, 11, 12]]
#### Since we selected 0, we are left with the first array:
#### [[1, 2, 3], [4, 5, 6]]

#### The second number represents the second dimension, which also contains two arrays:
#### [1, 2, 3]
####     &
#### [4, 5, 6]
#### Since we selected 1, we are left with the second array:
#### [4, 5, 6]

#### The third number represents the third dimension, which contains three values:
#### Since we selected 2, we end up with the third value: i.e 6

In [21]:
a = np.array([(1,2,3),(4,5,6)])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
## Size of each element
a.itemsize

8

In [20]:
## Size of Array
a.size

6

In [22]:
## Datatype of element
a.dtype

dtype('int64')

In [23]:
## Shape of Array
a.shape

(2, 3)

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
## Reshaping Array
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
## Flattening Array - > TO 1D
newarr = arr.reshape(-1)

In [27]:
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
a = np.array([(1,2,3),(4,5,6)])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
## Print Second index 
a[0:,2]

array([3, 6])

### Ufuncs -> Universal Functions in Numpy

In [24]:
## Creates an evenly spaced sequence in a specified interval
b = np.linspace(1,4,4)

In [25]:
b

array([1., 2., 3., 4.])

In [26]:
a = np.array([(1,2,3),(4,5,6)])

In [27]:
## Gets Max el of array
a.max()

6

In [28]:
## Gets Min el of array
a.min()

1

In [42]:
## Gets Sum of all el of array
a.sum()

21

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:

a.sum(axis=0)

array([5, 7, 9])

In [31]:

a.sum(axis=1)

array([ 6, 15])

In [37]:
## Sqrt
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [38]:
## Standard Deviation
np.std(a)

1.707825127659933

### Inplace & Out of Place

Inplace -> Changes the actual memory

Out of place -> Return the changed array

A= 4,5,1,8,9 -> SORT -> B= 1,4,5,8,9 (Inplace)

A

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6]])

#### Arithmetic Operations on 2 arrays

In [42]:
a1 = np.array([(1,2,3),(4,5,6)])

In [43]:
a2 = np.array([(1,2,3),(4,5,6)])

In [44]:
a1+a2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [45]:
a1-a2

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
a1*a2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [47]:
a1/a2

array([[1., 1., 1.],
       [1., 1., 1.]])

### Stacking Arrays

In [57]:
## Vertical Stacking
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
## Horizontal Stacking
np.hstack((a1,a2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Mathematical Functions

In [59]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [60]:
np.cos(a1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [61]:
np.tan(a1)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [62]:
np.exp(a1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [63]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [64]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [49]:
## Power

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

    
print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [53]:
newarr

array([         1000,       3200000,     729000000, 6553600000000,
                2500,             0])

In [50]:
arr1 ** arr2

array([         1000,       3200000,     729000000, 6553600000000,
                2500,             0])

In [67]:
## Modulus

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)


print(newarr)

[ 1  6  3  0  0 27]


In [69]:
## Absolute Values

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)


print(newarr)

[1 2 1 2 3 4]


In [70]:
## Rounding

arr = np.around(3.1666, 2)

print(arr)

3.17


In [74]:
## Product of all elements in an array

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [75]:
## GCD/HCF

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [76]:
## Degree to Radians

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [77]:
## Radians TO Degrees

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


### Advanced Numpy 

### COPY VS VIEW

### ARRAY COPY

In [78]:
arr = np.array([1,2,3])

In [80]:
x = arr.copy()

In [81]:
x

array([1, 2, 3])

In [82]:
arr[0] = 42

In [83]:
arr

array([42,  2,  3])

In [84]:
x

array([1, 2, 3])

a -> Memory Block 1
b = a ---> shallow copy -->  Memory Block 1 -> Passs by Reference ---> VIEW


a -> Memory Block 1

b = a.deepcopy() ---> b --> Memory Block 2 --> (5) --> Pass By Value ---> COPY



### VIEW

In [85]:
arr1 = np.array([1, 2, 3, 4, 5])

In [86]:
x1 = arr1.view()

In [87]:
#Changing Array
arr1[0] = 42

In [88]:
arr1

array([42,  2,  3,  4,  5])

In [89]:
x1

array([42,  2,  3,  4,  5])

In [90]:
#Changing View
x1[0] = 31

In [91]:
arr1

array([31,  2,  3,  4,  5])

In [92]:
x1

array([31,  2,  3,  4,  5])

### Iterating Numpy Array

In [67]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [68]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


In [69]:
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [101]:
## With Index Iteration

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [70]:
q = [1,2,3,4,5]

for idx, val in enumerate(q):
    print(idx,val)

0 1
1 2
2 3
3 4
4 5


### Splitting Array

In [81]:
## Split Array into multiple arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 8)

In [82]:
newarr

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int64),
 array([], dtype=int64)]

### Searching in an Array

In [84]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

In [85]:
x

(array([3, 5, 6]),)

In [86]:
type(x)

tuple

In [87]:
type(x[0])

numpy.ndarray

In [89]:
x[0][1]

5

In [111]:
## Get index where even values exist
x1 = np.where(arr%2 == 0)

In [112]:
x1[0]

array([1, 3, 5, 6])

### Sorting Array

In [113]:
np.sort(arr)

array([1, 2, 3, 4, 4, 4, 5])

#### Alphabetically Sort

In [114]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


### Boolean Sort

In [116]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


### Sorting a 2D Array

In [117]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Generating a Random Number

In [92]:
from numpy import random

In [93]:
x = random.randint(100)

In [94]:
x

58

### Generating a Random Float

In [95]:
x = random.rand()

In [96]:
x

0.9354442941199042

### Generating a Random Array from 0 to 100 permissible values

In [97]:
x=random.randint(100, size=(5))

In [98]:
x

array([35, 29, 72, 93, 29])

### Get random choice from an array

In [99]:
x = random.choice([3, 5, 7, 9])

In [100]:
x

3

### Shuffling Array Elements randomly

In [101]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr) #In place

In [102]:
arr

array([5, 4, 3, 2, 1])

In [103]:
b = random.permutation(arr)  #Out of place

In [104]:
b

array([3, 1, 2, 5, 4])